### ISSUE TITLE
改变状态栏颜色

### ISSUE THREAD

**Issue by cyztaobiao** [MummyDing/Leisure#17]
请问怎么实现通过改变colorPrimaryDark的属性值在android4.4的机子上改变状态栏颜色的？

**Comment by TakWolf** [comment]
android 4.4不支持改变状态栏颜色，请考虑如下方法实现：
 api >= 19 && api < 21，设置windowTranslucentStatus标志，让布局延伸到全屏，手动创建一个view模拟颜色状态栏

**Comment by cyztaobiao** [comment]
谢谢，我需要尝试一下。在你的源码中，我可以通过改变colorPrimaryDark的值来改变状态栏的颜色(API==19)，我暂时还没有找到你实现的过程代码，是通过MaterialDrawer实现的吗？

**Comment by TakWolf** [comment]
@litforest 
本人并非项目作者，仅对项目实现简单分析一下，不保证准确性

对于API 19(Android 4.4)，该项目并未真正实现沉浸式状态栏，实际上有沉浸式状态栏的只有MainActivity一个界面而已。在MainActivity中，作者使用的第三方来实现drawer效果（https://github.com/mikepenz/MaterialDrawer ），而这个第三方支持在api19下模拟颜色状态栏（https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/DrawerBuilder.java ）。

而DailyDetailActivity这个界面，布局也可以延伸到全屏是因为添加了windowTranslucentStatus标志，详见（https://github.com/MummyDing/Leisure/blob/master/app/src/main/java/com/mummyding/app/leisure/ui/support/BaseDetailsActivity.java#L87 ），作者本意是希望顶部图片可以延伸，但是恰巧这个在4.4上也有效果。这里的效果并不是颜色状态栏。

对于其他界面，例如AboutActivity，状态栏就是黑色的，4.4上没有做适配。

综上，该项目作者并未主动去适配API 19的沉浸式状态栏，只是某些界面恰巧有了沉浸式，相反由于一些原因，反而导致在API 19下，状态栏的实现效果不统一。

**Comment by TakWolf** [comment]
@litforest 如果想要实现一个沉浸式状态栏并且适配到API 19，一个可能的思路是：
对于api >= 21，使用系统默认的状态栏着色即可
对于api >= 19 && api < 21，添加如下标志：

```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT && Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
}
```

拦击setContentView，通过创建一个View模拟颜色状态栏

```
@Override
    public void setContentView(int layoutResId) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT && Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            FrameLayout rootView = new FrameLayout(this);
            rootView.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

            View contentView = LayoutInflater.from(this).inflate(layoutResId, rootView, false);
            contentView.setFitsSystemWindows(true);  // 此处注意，保证内容在状态栏下面
            rootView.addView(contentView);

            View statusBarView = new View(this);
            statusBarView.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ResUtils.getStatusBarHeight(this)));
            statusBarView.setBackgroundColor(Content.getColor(R.color.colorPrimaryDark));
            rootView.addView(statusBarView);

            super.setContentView(rootView);
        } else {
            super.setContentView(layoutResId);
        }
    }
```

获取状态栏高度的代码实现参考：

```
public static int getStatusBarHeight(@NonNull Context context) {
        int resourceId = context.getResources().getIdentifier("status_bar_height", "dimen", "android");
        return resourceId > 0 ? context.getResources().getDimensionPixelSize(resourceId) : 0;
}
```

**Comment by MummyDing** [comment]
哈哈，刚看到，你俩已经讨论得听high了。对于状态栏我确实没有对低版本做特殊处理，理论上对于4.4(不知道有没有记错)以下是没有沉浸效果的。如果有的话，也许是用到的几个开源库阴差阳错刚好有达到这个效果。

**Comment by cyztaobiao** [comment]
@TakWolf 没有注意抱歉。你的思路很清晰，让我豁然开朗。确实是因为开源库的关系，我想我要熟悉一下MaterialDrawer中statusbar的具体实现，非常感谢两位的解答。
