### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by vjackman** [MummyDing/Leisure#19]
Please Post Backend Code

**Comment by MummyDing** [comment]
@vjackman  There is no backend code, all data are provided by public api.

**Comment by vjackman** [comment]
What if I need to input my data? I have no knowledge about public api

**Comment by MummyDing** [comment]
Leisure's data is from the third party websites: Zhihu, Guokr etc. I just capture their request so I can get the data.Leisure does not have its own server.Those third party websites are not open source, and we cannot modify their data.

**Comment by vjackman** [comment]
Then how can I use for my project?

**Comment by MummyDing** [comment]
What do you mean?  You want Leisure's data?

**Comment by vjackman** [comment]
I mean is it just for contributing or I can use for my own production?

**Comment by MummyDing** [comment]
Maybe it not exactly helpful for your production, it's just a Chinese reading app. I post it for Android Beginners who have no idea how to develop a new app from the beginning.

**Comment by vjackman** [comment]
Oh is it!! Can you do custom development for us? A paid work?

**Comment by MummyDing** [comment]
It's interesting.Can you provider for more details? You can send by email:MummyDing@outlook.com

**Comment by vjackman** [comment]
Please check your email

**Comment by MummyDing** [comment]
okay，I will reply you later.
